---
# 0. RBAC per permettere all'app di leggere le info dei Nodi
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flask-node-reader-binding
subjects:
- kind: ServiceAccount
  name: flask-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io

---
# 1. Secret per le credenziali di MariaDB
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: default
spec:
  encryptedData:
    MYSQL_DATABASE: AgBW8VOOYBT8DEqqRb6arwryA+YKALVX8j4+26wMBcl+B1f706e9QVTsx63CSI7Yyqn+pjWNhWymmELWgOpruxGkMqr4DeXy9JBMm5KohoV7LadE/AnlVda6TzU5vojpJLW6YyA7hgEcfoDSk2mJslF7yLUomDhUzR/Dbv9iKpje6T3QWqvg7g+z/T1VQEKojlNQ1Ku5cHHvIPJP7sMOrzDd+eQo0PKT93ifMjFRNKQOVSwBvsAz6AQe6CmBTvAUjmJPVJ6SHO5V9U/ZT8Vr6KsC6yvV2bE1j3e/dzx1lRCjHvQayLnJbdg8UWBN+59lCs5vPpa4DnPP4u/7yad9DZO8tzkO8QXaNJSlSpZ5i7r3MzSloTBbHyX4i7shmv+++tMi07AndHkcrGmngZmn/u+3G5LmQm9/r7p44gIMIeD1kWMQcOeFj27Xsn4DcxPHzqm/s1mhrfrXX9hbzS6KVYMI+NjcBG3ksCicM+ED9W1OUU/xkpGPyd5vIwIoNUR3UNcLwKzUNCHuT7GPiAfbNLoAPfhGEQR/iNs+V9tgxbdU00+znBQC7TL3uPkM0XdjCJ3dJm6HHhEneUExJO1gaXYaFy4dCFdoDlt9bsmbpD01SZScKAoAWI0lgeX7LjJHGvtwrC7lSHIIOd2o8HZain60SjCq+d3x26EQPpj22El6Mo+b54hvdRnDIX5+B/L7wxxq2bcuvtNbc9o=
    MYSQL_ROOT_PASSWORD: AgBHkvmvnTq7Q5Y7mjh1qpmJs6Y+4Pr6kPxCgN+8uAtLC2vNib7HxI3gwHRvwKJQkK9XJzW6yz1QY5/V9qdSvgKY5aRP62OHEu/NQgDwRPdIXf17FIWzGolIAgMZs+Ok/1Hhve44o3sN83xNAIjCOvDMgm/Eo+LzkrLkIvr4K9/vH5csab9cf8wDTy7YWDNHB4s5lJ5a1qNzJgDnt45o+Adl+Ip3sozgPRyr0xRXu9srIrM+KNvNBuXUSH722AT/tf3RbEdH4A8mNZBkMGMN7q5f4f6KVqMwIwLXkXz7OslWMl8N7ZCpMbYeju8kIIkg7Jdf9130LIb/wfkxVk+1097jwEGlq9zHE9mOyla4ICqe3T2BLRFTJQeXhoRgngzBtqcUhv7yK7wkr/B2UZfvgx7g4Orju2Dt0HpribQkcTz+9VpdHjqFOIpdISwqrQ+TNbXYtIreJpJp9rZHmOoMYzrteWlTGsL4ztXXCgJcCNJ+OhfAegFrrnfI6uPoAryciJLw+T0v1UK6HVSgCV9ICtio1X597a+3IhTnSdudvyN9PRFr4B7SYtUSakQOTOQZgxmuAv7zE2dYP1prJyhfo0cTHR1j/psJ5bmEEI3+LgptfqwhJCAResAx2q/GDkVbY7we16gQ5+5+SjHxurmByL2PkRg4OlOONTYssIiw8V6cCASA0xvJ3K8PrKTQWRVyyGIaG1/+wpKzGA==
  template:
    metadata:
      name: mysql-secret
      namespace: default
    type: Opaque
---
# 2. Persistent Volume Claim (Richiesta di disco per MySQL)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
# 3. Database MySQL (StatefulSet invece di Deployment!)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mariadb:10.11
        envFrom:
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---
# 4. Service per MySQL (ClusterIP, visibile solo dentro al cluster)
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
# 5. Cache Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379

---
# 6. Service per Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
# 7. App Flask (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: flask-sa
      containers:
      - name: flask
        image: <CONTROL_NODE_IP>:5000/flask-k8s-app:latest
        imagePullPolicy: Always 
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DB
          value: "guestbook"
        ports:
        - containerPort: 5000

---
# 8. Service per Flask (ClusterIP, accessibile tramite Ingress)
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
# 9. Ingress (Il Portiere)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: flask.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-service
            port:
              number: 5000
