name: Build and Deploy to K3s

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'               # Si attiva se modifichi l'app
      - '3_kubernetes/**'      # O se modifichi i file Kubernetes!

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Podman image
        run: |
          cd app
          podman build -t ${{ secrets.REGISTRY_IP }}:5000/flask-k8s-app:latest .

      - name: Push to local registry
        run: podman push ${{ secrets.REGISTRY_IP }}:5000/flask-k8s-app:latest

      - name: Deploy to Kubernetes
        run: |
          # Sostituisce il placeholder con l'IP del secret
          sed 's/<CONTROL_NODE_IP>/${{ secrets.REGISTRY_IP }}/g' 3_kubernetes/app-deployment.yaml > temp-deploy.yaml
          # Applica il file al cluster
          kubectl apply -f temp-deploy.yaml
          # Forza il riavvio dei pod per scaricare la nuova immagine
          kubectl rollout restart deployment/flask-app
